name: Terraform
on:
  pull_request:
    branches:
      - main

jobs:
  tflint:
    name: tflint
    runs-on: [self-hosted, amd64]

    steps:
      - uses: actions/checkout@v3
        name: Checkout source code

      - uses: actions/cache@v3
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: v0.42.2

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Enable matchers
        run: echo ::add-matcher::.github/tflint-matchers.json

      - name: Run TFlint
        run: tflint -f compact
