name: Terraform

on:
  pull_request:
    branches:
      - main

jobs:
  trivy:
    permissions:
      contents: read
      actions: read
      security-events: write

    runs-on:
      group: arc-public-large-amd64-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        env:
          TRIVY_TF_EXCLUDE_DOWNLOADED_MODULES: "true"
        with:
          cache: true
          exit-code: "1"
          format: "table"
          hide-progress: false
          ignore-unfixed: true
          scan-ref: "."
          scan-type: "config"
          severity: HIGH,CRITICAL
