name: Terraform

on:
  pull_request:
    branches:
      - main

jobs:
  trivy:
    permissions:
      contents: read
      actions: read
      security-events: write

    runs-on:
      group: arc-public-large-amd64-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1
        env:
          TRIVY_TF_EXCLUDE_DOWNLOADED_MODULES: "true"
        with:
          cache: true
          exit-code: "1"
          format: "table"
          hide-progress: false
          ignore-unfixed: true
          scan-ref: "."
          scan-type: "config"
          severity: HIGH,CRITICAL
